"""Add status/error to Track (as varchar), nullable manifest, index status

Revision ID: b14bc0ebfaac
Revises: 119db4f8cf14
Create Date: 2025-04-19 16:35:29.094311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b14bc0ebfaac'
down_revision = '119db4f8cf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'ERROR', name='trackstatus', native_enum=False), nullable=False, server_default='PENDING'))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.alter_column('manifest_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('manifest_type',
               existing_type=postgresql.ENUM('HLS', 'DASH', name='manifesttype'),
               type_=sa.Enum('HLS', 'DASH', name='manifesttype', native_enum=False),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_tracks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_status'))
        batch_op.alter_column('manifest_type',
               existing_type=sa.Enum('HLS', 'DASH', name='manifesttype', native_enum=False),
               type_=postgresql.ENUM('HLS', 'DASH', name='manifesttype'),
               nullable=False)
        batch_op.alter_column('manifest_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
